# Generated by Django 4.0.3 on 2022-05-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='code',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
