# Generated by Django 4.0.3 on 2022-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_users_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='is_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='finalprice',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='model_year',
            field=models.IntegerField(),
        ),
    ]
