# Generated by Django 4.0.3 on 2022-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_bet_is_win_alter_offer_finalprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='finalprice',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
