# Generated by Django 4.0.3 on 2022-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_offer_endingbet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_online',
        ),
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
